from car_agent.state import load_and_compress
from car_agent.graph import build_graph

# Initialize graph once at module level
_graph = build_graph()

def analyze_image_path(image_path: str) -> dict:
    """
    Analyze vehicle damage from image for insurance claim assessment.
    
    Args:
        image_path: Path to image file
        
    Returns:
        dict: Damage assessment results with claim decision and recommendations
        
    Raises:
        ValueError: If image is invalid or cannot be processed
        RuntimeError: If analysis pipeline fails
    """
    try:
        image_base64 = load_and_compress(image_path)
    except ValueError as e:
        raise ValueError(f"Image processing failed: {str(e)}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error loading image: {str(e)}")
    
    initial_state = {
        "image_base64": image_base64,
        "damage_category": "",
        "damage_description": "",
        "incident_context": "",
        "filter_result": {},
        "should_skip_assessment": False,
        "relevant_checks": [],
        "damage_analysis": [],
        "flagged_damages": [],
        "claim_recommendations": [],
        "affected_areas": [],
        "overall_severity_level": "",
        "estimated_total_cost": "",
        "fraud_indicators": [],
        "action_recommendations": [],
        "action_selection_reasoning": "",
        "messages": []
    }
    
    try:
        final_state = _graph.invoke(initial_state)
    except Exception as e:
        print(f"⚠️ Graph execution failed: {e}")
        raise RuntimeError(f"Analysis pipeline failed: {str(e)}")
    
    # Handle case where photo validation failed
    if final_state.get("should_skip_assessment"):
        filter_result = final_state.get("filter_result") or {}
        return {
            "image_path": image_path,
            "damage_category": final_state.get("damage_category", ""),
            "damage_description": final_state.get("damage_description", ""),
            "incident_context": final_state.get("incident_context", ""),
            "photo_valid": False,
            "skip_reason": filter_result.get(
                "reason",
                "Image not suitable for damage assessment."
            ),
            "damage_analysis": [],
            "flagged_damages": [],
            "claim_decision": "REJECT",
            "recommended_actions": ["Submit clearer photos showing damage"],
            "affected_areas": [],
            "overall_severity": "NONE",
            "estimated_cost": "$0",
            "fraud_indicators": [],
            "next_actions": []
        }
    
    # Extract claim recommendations
    claim_recommendations = final_state.get("claim_recommendations", [])
    if not claim_recommendations:
        print("⚠️ Warning: No claim recommendations generated by pipeline")
        return {
            "image_path": image_path,
            "damage_category": final_state.get("damage_category", "UNKNOWN"),
            "damage_description": final_state.get("damage_description", ""),
            "incident_context": final_state.get("incident_context", ""),
            "photo_valid": True,
            "skip_reason": None,
            "damage_analysis": final_state.get("damage_analysis", []),
            "flagged_damages": final_state.get("flagged_damages", []),
            "claim_decision": "INVESTIGATE",
            "recommended_actions": [
                "Manual review required - automated assessment incomplete"
            ],
            "affected_areas": [],
            "overall_severity": "UNDETERMINED",
            "estimated_cost": "TBD",
            "fraud_indicators": [],
            "next_actions": []
        }
    
    # Format successful response
    claim_rec = claim_recommendations[0]
    
    return {
        "image_path": image_path,
        "damage_category": final_state.get("damage_category", ""),
        "damage_description": final_state.get("damage_description", ""),
        "incident_context": final_state.get("incident_context", ""),
        "photo_valid": True,
        "skip_reason": None,
        
        # Damage analysis
        "damage_analysis": final_state.get("damage_analysis", []),
        "flagged_damages": final_state.get("flagged_damages", []),
        "affected_areas": final_state.get("affected_areas", []),
        
        # Claim decision
        "claim_decision": claim_rec.get("claim_decision", "INVESTIGATE"),
        "recommended_actions": claim_rec.get("recommended_actions", []),
        "overall_severity": final_state.get("overall_severity_level", "UNDETERMINED"),
        "estimated_cost": final_state.get("estimated_total_cost", "TBD"),
        
        # Fraud detection
        "fraud_indicators": final_state.get("fraud_indicators", []),
        
        # Next actions
        "next_actions": final_state.get("action_recommendations", []),
        "action_reasoning": final_state.get("action_selection_reasoning", "")
    }
