from ergo_agent.state import load_and_compress
from ergo_agent.graph import create_ergonomic_agent_graph

# Initialize graph once at module level
_graph = create_ergonomic_agent_graph()


def analyze_image_path(image_path: str) -> dict:
    """
    Analyze an image for ergonomic risks.

    Args:
        image_path: Path to image file

    Returns:
        dict: Analysis results with risk assessment and recommendations

    Raises:
        ValueError: If image is invalid or cannot be processed
        RuntimeError: If analysis pipeline fails
    """
    try:
        image_base64 = load_and_compress(image_path)
    except ValueError as e:
        # Invalid image or compression failed (already has good message)
        raise ValueError(f"Image processing failed: {str(e)}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error loading image: {str(e)}")

    initial_state = {
        "image_base64": image_base64,
        "image_path": image_path,
        "activity_category": "",
        "activity_title": "",
        "scene_context": "",
        "relevant_checks": [],
        "risk_analysis": [],
        "flagged_risks": [],
        "recommendations": [],
        "overall_risk_level": None,
        "messages": [],
        "should_skip_ergonomics": False,
        "filter_result": None,
        "affected_body_regions": [],
    }

    try:
        final_state = _graph.invoke(initial_state)
    except Exception as e:
        print(f"⚠️ Graph execution failed: {e}")
        raise RuntimeError(f"Analysis pipeline failed: {str(e)}")

    if final_state.get("should_skip_ergonomics"):
        filter_result = final_state.get("filter_result") or {}
        return {
            "image_path": image_path,
            "activity_category": final_state.get("activity_category", ""),
            "activity_title": final_state.get("activity_title", ""),
            "scene_context": final_state.get("scene_context", ""),
            "skipped": True,
            "skip_reason": filter_result.get(
                "reason",
                "Image not suitable for ergonomic assessment."
            ),
            "risk_analysis": [],
            "observed_risks": [],
            "recommendations": [],
            "overall_risk_level": None,
        }

    recommendations_list = final_state.get("recommendations", [])

    if not recommendations_list:
        print("⚠️ Warning: No recommendations generated by pipeline")
        return {
            "image_path": image_path,
            "activity_category": final_state.get("activity_category", "UNKNOWN"),
            "activity_title": final_state.get("activity_title", ""),
            "scene_context": final_state.get("scene_context", ""),
            "skipped": False,
            "skip_reason": None,
            "risk_analysis": final_state.get("risk_analysis", []),
            "observed_risks": [],
            "recommendations": [
                "Analysis completed but no specific recommendations were generated."
            ],
            "overall_risk_level": "UNDETERMINED",
        }

    rec = recommendations_list[0]

    return {
        "image_path": image_path,
        "activity_category": final_state.get("activity_category", ""),
        "activity_title": final_state.get("activity_title", ""),
        "scene_context": final_state.get("scene_context", ""),
        "skipped": False,
        "skip_reason": None,
        "risk_analysis": final_state.get("risk_analysis", []),
        "observed_risks": rec.get("observed_risks", []),
        "recommendations": rec.get("recommendations", []),
        "overall_risk_level": rec.get("overall_risk_level", "UNDETERMINED"),
    }
